// flow-typed signature: 584180b9927e39e0a7e9753f85743ded
// flow-typed version: <<STUB>>/@semantic-release/changelog_v^5.0.1/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@semantic-release/changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@semantic-release/changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@semantic-release/changelog/lib/definitions/errors' {
  declare module.exports: any;
}

declare module '@semantic-release/changelog/lib/get-error' {
  declare module.exports: any;
}

declare module '@semantic-release/changelog/lib/prepare' {
  declare module.exports: any;
}

declare module '@semantic-release/changelog/lib/resolve-config' {
  declare module.exports: any;
}

declare module '@semantic-release/changelog/lib/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module '@semantic-release/changelog/index' {
  declare module.exports: $Exports<'@semantic-release/changelog'>;
}
declare module '@semantic-release/changelog/index.js' {
  declare module.exports: $Exports<'@semantic-release/changelog'>;
}
declare module '@semantic-release/changelog/lib/definitions/errors.js' {
  declare module.exports: $Exports<'@semantic-release/changelog/lib/definitions/errors'>;
}
declare module '@semantic-release/changelog/lib/get-error.js' {
  declare module.exports: $Exports<'@semantic-release/changelog/lib/get-error'>;
}
declare module '@semantic-release/changelog/lib/prepare.js' {
  declare module.exports: $Exports<'@semantic-release/changelog/lib/prepare'>;
}
declare module '@semantic-release/changelog/lib/resolve-config.js' {
  declare module.exports: $Exports<'@semantic-release/changelog/lib/resolve-config'>;
}
declare module '@semantic-release/changelog/lib/verify.js' {
  declare module.exports: $Exports<'@semantic-release/changelog/lib/verify'>;
}
