// flow-typed signature: 98ae2cb4471d735f9dc04c8662ebabaf
// flow-typed version: <<STUB>>/@semantic-release/git_v^9.0.0/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@semantic-release/git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@semantic-release/git' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@semantic-release/git/lib/definitions/errors' {
  declare module.exports: any;
}

declare module '@semantic-release/git/lib/get-error' {
  declare module.exports: any;
}

declare module '@semantic-release/git/lib/git' {
  declare module.exports: any;
}

declare module '@semantic-release/git/lib/prepare' {
  declare module.exports: any;
}

declare module '@semantic-release/git/lib/resolve-config' {
  declare module.exports: any;
}

declare module '@semantic-release/git/lib/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module '@semantic-release/git/index' {
  declare module.exports: $Exports<'@semantic-release/git'>;
}
declare module '@semantic-release/git/index.js' {
  declare module.exports: $Exports<'@semantic-release/git'>;
}
declare module '@semantic-release/git/lib/definitions/errors.js' {
  declare module.exports: $Exports<'@semantic-release/git/lib/definitions/errors'>;
}
declare module '@semantic-release/git/lib/get-error.js' {
  declare module.exports: $Exports<'@semantic-release/git/lib/get-error'>;
}
declare module '@semantic-release/git/lib/git.js' {
  declare module.exports: $Exports<'@semantic-release/git/lib/git'>;
}
declare module '@semantic-release/git/lib/prepare.js' {
  declare module.exports: $Exports<'@semantic-release/git/lib/prepare'>;
}
declare module '@semantic-release/git/lib/resolve-config.js' {
  declare module.exports: $Exports<'@semantic-release/git/lib/resolve-config'>;
}
declare module '@semantic-release/git/lib/verify.js' {
  declare module.exports: $Exports<'@semantic-release/git/lib/verify'>;
}
