// flow-typed signature: ed9da1a0cd97ab6d6fc32586fd8a41c4
// flow-typed version: <<STUB>>/@commitlint/cli_v^9.1.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/cli/lib/cli' {
  declare module.exports: any;
}

declare module '@commitlint/cli/lib/help' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/cli/index' {
  declare module.exports: $Exports<'@commitlint/cli'>;
}
declare module '@commitlint/cli/index.js' {
  declare module.exports: $Exports<'@commitlint/cli'>;
}
declare module '@commitlint/cli/lib/cli.js' {
  declare module.exports: $Exports<'@commitlint/cli/lib/cli'>;
}
declare module '@commitlint/cli/lib/help.js' {
  declare module.exports: $Exports<'@commitlint/cli/lib/help'>;
}
