// flow-typed signature: d79bc556c50e3ae0263d1783c0edd2a0
// flow-typed version: <<STUB>>/eslint-plugin-testing-library_v^3.3.1/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-testing-library/node-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/await-async-query' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/await-async-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/await-fire-event' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/consistent-data-testid' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-await-sync-query' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-debug' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-dom-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-manual-cleanup' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-wait-for-empty-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-explicit-assert' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-find-by' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-presence-queries' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-screen-queries' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-wait-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-testing-library/index' {
  declare module.exports: $Exports<'eslint-plugin-testing-library'>;
}
declare module 'eslint-plugin-testing-library/index.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library'>;
}
declare module 'eslint-plugin-testing-library/node-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/node-utils'>;
}
declare module 'eslint-plugin-testing-library/rules/await-async-query.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/await-async-query'>;
}
declare module 'eslint-plugin-testing-library/rules/await-async-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/await-async-utils'>;
}
declare module 'eslint-plugin-testing-library/rules/await-fire-event.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/await-fire-event'>;
}
declare module 'eslint-plugin-testing-library/rules/consistent-data-testid.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/consistent-data-testid'>;
}
declare module 'eslint-plugin-testing-library/rules/no-await-sync-query.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-await-sync-query'>;
}
declare module 'eslint-plugin-testing-library/rules/no-debug.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-debug'>;
}
declare module 'eslint-plugin-testing-library/rules/no-dom-import.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-dom-import'>;
}
declare module 'eslint-plugin-testing-library/rules/no-manual-cleanup.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-manual-cleanup'>;
}
declare module 'eslint-plugin-testing-library/rules/no-wait-for-empty-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-wait-for-empty-callback'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-explicit-assert.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-explicit-assert'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-find-by.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-find-by'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-presence-queries.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-presence-queries'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-screen-queries.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-screen-queries'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-wait-for.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-wait-for'>;
}
declare module 'eslint-plugin-testing-library/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/utils'>;
}
