// flow-typed signature: 1fe87a24321082722a4741e6b8940d2b
// flow-typed version: <<STUB>>/eslint-plugin-jest-dom_v^3.1.4/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jest-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jest-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jest-dom/dist/createBannedAttributeRule' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest-dom/dist' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest-dom/dist/rules/prefer-checked' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest-dom/dist/rules/prefer-empty' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest-dom/dist/rules/prefer-enabled-disabled' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest-dom/dist/rules/prefer-focus' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest-dom/dist/rules/prefer-required' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest-dom/dist/rules/prefer-to-have-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest-dom/dist/rules/prefer-to-have-text-content' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jest-dom/dist/createBannedAttributeRule.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist/createBannedAttributeRule'>;
}
declare module 'eslint-plugin-jest-dom/dist/index' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist'>;
}
declare module 'eslint-plugin-jest-dom/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist'>;
}
declare module 'eslint-plugin-jest-dom/dist/rules/prefer-checked.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist/rules/prefer-checked'>;
}
declare module 'eslint-plugin-jest-dom/dist/rules/prefer-empty.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist/rules/prefer-empty'>;
}
declare module 'eslint-plugin-jest-dom/dist/rules/prefer-enabled-disabled.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist/rules/prefer-enabled-disabled'>;
}
declare module 'eslint-plugin-jest-dom/dist/rules/prefer-focus.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist/rules/prefer-focus'>;
}
declare module 'eslint-plugin-jest-dom/dist/rules/prefer-required.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist/rules/prefer-required'>;
}
declare module 'eslint-plugin-jest-dom/dist/rules/prefer-to-have-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist/rules/prefer-to-have-attribute'>;
}
declare module 'eslint-plugin-jest-dom/dist/rules/prefer-to-have-text-content.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/dist/rules/prefer-to-have-text-content'>;
}
