// flow-typed signature: 9f67934c35f0c5d41c28c15d8c2d8a0d
// flow-typed version: <<STUB>>/globby_v^11.0.1/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'globby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'globby/gitignore' {
  declare module.exports: any;
}

declare module 'globby/stream-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'globby/gitignore.js' {
  declare module.exports: $Exports<'globby/gitignore'>;
}
declare module 'globby/index' {
  declare module.exports: $Exports<'globby'>;
}
declare module 'globby/index.js' {
  declare module.exports: $Exports<'globby'>;
}
declare module 'globby/stream-utils.js' {
  declare module.exports: $Exports<'globby/stream-utils'>;
}
