// flow-typed signature: 1fe8f4f40fcb91e64b0c07c21d473f61
// flow-typed version: <<STUB>>/miragejs_v^0.1.41/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'miragejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'miragejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'miragejs/babel.config' {
  declare module.exports: any;
}

declare module 'miragejs/dist/mirage-cjs' {
  declare module.exports: any;
}

declare module 'miragejs/dist/mirage-esm' {
  declare module.exports: any;
}

declare module 'miragejs/dist/mirage-umd' {
  declare module.exports: any;
}

declare module 'miragejs/jest.config' {
  declare module.exports: any;
}

declare module 'miragejs/lib/assert' {
  declare module.exports: any;
}

declare module 'miragejs/lib/association' {
  declare module.exports: any;
}

declare module 'miragejs/lib/container' {
  declare module.exports: any;
}

declare module 'miragejs/lib/db-collection' {
  declare module.exports: any;
}

declare module 'miragejs/lib/db' {
  declare module.exports: any;
}

declare module 'miragejs/lib/factory' {
  declare module.exports: any;
}

declare module 'miragejs/lib/identity-manager' {
  declare module.exports: any;
}

declare module 'miragejs/lib' {
  declare module.exports: any;
}

declare module 'miragejs/lib/orm/associations/association' {
  declare module.exports: any;
}

declare module 'miragejs/lib/orm/associations/belongs-to' {
  declare module.exports: any;
}

declare module 'miragejs/lib/orm/associations/has-many' {
  declare module.exports: any;
}

declare module 'miragejs/lib/orm/collection' {
  declare module.exports: any;
}

declare module 'miragejs/lib/orm/model' {
  declare module.exports: any;
}

declare module 'miragejs/lib/orm/polymorphic-collection' {
  declare module.exports: any;
}

declare module 'miragejs/lib/orm/schema' {
  declare module.exports: any;
}

declare module 'miragejs/lib/response' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handler' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handlers/base' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handlers/function' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handlers/object' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handlers/shorthands/base' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handlers/shorthands/delete' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handlers/shorthands/get' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handlers/shorthands/head' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handlers/shorthands/post' {
  declare module.exports: any;
}

declare module 'miragejs/lib/route-handlers/shorthands/put' {
  declare module.exports: any;
}

declare module 'miragejs/lib/serializer-registry' {
  declare module.exports: any;
}

declare module 'miragejs/lib/serializer' {
  declare module.exports: any;
}

declare module 'miragejs/lib/serializers/active-model-serializer' {
  declare module.exports: any;
}

declare module 'miragejs/lib/serializers/json-api-serializer' {
  declare module.exports: any;
}

declare module 'miragejs/lib/serializers/rest-serializer' {
  declare module.exports: any;
}

declare module 'miragejs/lib/server' {
  declare module.exports: any;
}

declare module 'miragejs/lib/trait' {
  declare module.exports: any;
}

declare module 'miragejs/lib/utils/extend' {
  declare module.exports: any;
}

declare module 'miragejs/lib/utils/inflector' {
  declare module.exports: any;
}

declare module 'miragejs/lib/utils/is-association' {
  declare module.exports: any;
}

declare module 'miragejs/lib/utils/reference-sort' {
  declare module.exports: any;
}

declare module 'miragejs/lib/utils/uuid' {
  declare module.exports: any;
}

declare module 'miragejs/prettier.config' {
  declare module.exports: any;
}

declare module 'miragejs/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'miragejs/babel.config.js' {
  declare module.exports: $Exports<'miragejs/babel.config'>;
}
declare module 'miragejs/dist/mirage-cjs.js' {
  declare module.exports: $Exports<'miragejs/dist/mirage-cjs'>;
}
declare module 'miragejs/dist/mirage-esm.js' {
  declare module.exports: $Exports<'miragejs/dist/mirage-esm'>;
}
declare module 'miragejs/dist/mirage-umd.js' {
  declare module.exports: $Exports<'miragejs/dist/mirage-umd'>;
}
declare module 'miragejs/index' {
  declare module.exports: $Exports<'miragejs'>;
}
declare module 'miragejs/index.js' {
  declare module.exports: $Exports<'miragejs'>;
}
declare module 'miragejs/jest.config.js' {
  declare module.exports: $Exports<'miragejs/jest.config'>;
}
declare module 'miragejs/lib/assert.js' {
  declare module.exports: $Exports<'miragejs/lib/assert'>;
}
declare module 'miragejs/lib/association.js' {
  declare module.exports: $Exports<'miragejs/lib/association'>;
}
declare module 'miragejs/lib/container.js' {
  declare module.exports: $Exports<'miragejs/lib/container'>;
}
declare module 'miragejs/lib/db-collection.js' {
  declare module.exports: $Exports<'miragejs/lib/db-collection'>;
}
declare module 'miragejs/lib/db.js' {
  declare module.exports: $Exports<'miragejs/lib/db'>;
}
declare module 'miragejs/lib/factory.js' {
  declare module.exports: $Exports<'miragejs/lib/factory'>;
}
declare module 'miragejs/lib/identity-manager.js' {
  declare module.exports: $Exports<'miragejs/lib/identity-manager'>;
}
declare module 'miragejs/lib/index' {
  declare module.exports: $Exports<'miragejs/lib'>;
}
declare module 'miragejs/lib/index.js' {
  declare module.exports: $Exports<'miragejs/lib'>;
}
declare module 'miragejs/lib/orm/associations/association.js' {
  declare module.exports: $Exports<'miragejs/lib/orm/associations/association'>;
}
declare module 'miragejs/lib/orm/associations/belongs-to.js' {
  declare module.exports: $Exports<'miragejs/lib/orm/associations/belongs-to'>;
}
declare module 'miragejs/lib/orm/associations/has-many.js' {
  declare module.exports: $Exports<'miragejs/lib/orm/associations/has-many'>;
}
declare module 'miragejs/lib/orm/collection.js' {
  declare module.exports: $Exports<'miragejs/lib/orm/collection'>;
}
declare module 'miragejs/lib/orm/model.js' {
  declare module.exports: $Exports<'miragejs/lib/orm/model'>;
}
declare module 'miragejs/lib/orm/polymorphic-collection.js' {
  declare module.exports: $Exports<'miragejs/lib/orm/polymorphic-collection'>;
}
declare module 'miragejs/lib/orm/schema.js' {
  declare module.exports: $Exports<'miragejs/lib/orm/schema'>;
}
declare module 'miragejs/lib/response.js' {
  declare module.exports: $Exports<'miragejs/lib/response'>;
}
declare module 'miragejs/lib/route-handler.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handler'>;
}
declare module 'miragejs/lib/route-handlers/base.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handlers/base'>;
}
declare module 'miragejs/lib/route-handlers/function.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handlers/function'>;
}
declare module 'miragejs/lib/route-handlers/object.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handlers/object'>;
}
declare module 'miragejs/lib/route-handlers/shorthands/base.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handlers/shorthands/base'>;
}
declare module 'miragejs/lib/route-handlers/shorthands/delete.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handlers/shorthands/delete'>;
}
declare module 'miragejs/lib/route-handlers/shorthands/get.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handlers/shorthands/get'>;
}
declare module 'miragejs/lib/route-handlers/shorthands/head.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handlers/shorthands/head'>;
}
declare module 'miragejs/lib/route-handlers/shorthands/post.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handlers/shorthands/post'>;
}
declare module 'miragejs/lib/route-handlers/shorthands/put.js' {
  declare module.exports: $Exports<'miragejs/lib/route-handlers/shorthands/put'>;
}
declare module 'miragejs/lib/serializer-registry.js' {
  declare module.exports: $Exports<'miragejs/lib/serializer-registry'>;
}
declare module 'miragejs/lib/serializer.js' {
  declare module.exports: $Exports<'miragejs/lib/serializer'>;
}
declare module 'miragejs/lib/serializers/active-model-serializer.js' {
  declare module.exports: $Exports<'miragejs/lib/serializers/active-model-serializer'>;
}
declare module 'miragejs/lib/serializers/json-api-serializer.js' {
  declare module.exports: $Exports<'miragejs/lib/serializers/json-api-serializer'>;
}
declare module 'miragejs/lib/serializers/rest-serializer.js' {
  declare module.exports: $Exports<'miragejs/lib/serializers/rest-serializer'>;
}
declare module 'miragejs/lib/server.js' {
  declare module.exports: $Exports<'miragejs/lib/server'>;
}
declare module 'miragejs/lib/trait.js' {
  declare module.exports: $Exports<'miragejs/lib/trait'>;
}
declare module 'miragejs/lib/utils/extend.js' {
  declare module.exports: $Exports<'miragejs/lib/utils/extend'>;
}
declare module 'miragejs/lib/utils/inflector.js' {
  declare module.exports: $Exports<'miragejs/lib/utils/inflector'>;
}
declare module 'miragejs/lib/utils/is-association.js' {
  declare module.exports: $Exports<'miragejs/lib/utils/is-association'>;
}
declare module 'miragejs/lib/utils/reference-sort.js' {
  declare module.exports: $Exports<'miragejs/lib/utils/reference-sort'>;
}
declare module 'miragejs/lib/utils/uuid.js' {
  declare module.exports: $Exports<'miragejs/lib/utils/uuid'>;
}
declare module 'miragejs/prettier.config.js' {
  declare module.exports: $Exports<'miragejs/prettier.config'>;
}
declare module 'miragejs/rollup.config.js' {
  declare module.exports: $Exports<'miragejs/rollup.config'>;
}
