// flow-typed signature: da3a2c4175b71b02cdaf9d19c7717ccd
// flow-typed version: <<STUB>>/normalize-package-data_v^2.5.0/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-package-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-package-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'normalize-package-data/lib/extract_description' {
  declare module.exports: any;
}

declare module 'normalize-package-data/lib/fixer' {
  declare module.exports: any;
}

declare module 'normalize-package-data/lib/make_warning' {
  declare module.exports: any;
}

declare module 'normalize-package-data/lib/normalize' {
  declare module.exports: any;
}

declare module 'normalize-package-data/lib/safe_format' {
  declare module.exports: any;
}

// Filename aliases
declare module 'normalize-package-data/lib/extract_description.js' {
  declare module.exports: $Exports<'normalize-package-data/lib/extract_description'>;
}
declare module 'normalize-package-data/lib/fixer.js' {
  declare module.exports: $Exports<'normalize-package-data/lib/fixer'>;
}
declare module 'normalize-package-data/lib/make_warning.js' {
  declare module.exports: $Exports<'normalize-package-data/lib/make_warning'>;
}
declare module 'normalize-package-data/lib/normalize.js' {
  declare module.exports: $Exports<'normalize-package-data/lib/normalize'>;
}
declare module 'normalize-package-data/lib/safe_format.js' {
  declare module.exports: $Exports<'normalize-package-data/lib/safe_format'>;
}
