// flow-typed signature: 2dafdc42da952ffe10ad250cb06c3c86
// flow-typed version: <<STUB>>/read-pkg_v^5.2.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'read-pkg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'read-pkg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'read-pkg/index' {
  declare module.exports: $Exports<'read-pkg'>;
}
declare module 'read-pkg/index.js' {
  declare module.exports: $Exports<'read-pkg'>;
}
