// flow-typed signature: 393a0d91373ab7108a67fad321900bad
// flow-typed version: <<STUB>>/remark-lint-no-dead-urls_v^1.0.2/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-no-dead-urls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-no-dead-urls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-lint-no-dead-urls/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-lint-no-dead-urls/index' {
  declare module.exports: $Exports<'remark-lint-no-dead-urls'>;
}
declare module 'remark-lint-no-dead-urls/index.js' {
  declare module.exports: $Exports<'remark-lint-no-dead-urls'>;
}
declare module 'remark-lint-no-dead-urls/test.js' {
  declare module.exports: $Exports<'remark-lint-no-dead-urls/test'>;
}
