// flow-typed signature: c571149e32654f29a685dbd89a78fb8b
// flow-typed version: <<STUB>>/rollup-plugin-copy_v^3.3.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-copy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-copy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-copy/dist/index.commonjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-copy/dist/index.module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-copy/dist/index.commonjs.js' {
  declare module.exports: $Exports<'rollup-plugin-copy/dist/index.commonjs'>;
}
declare module 'rollup-plugin-copy/dist/index.module.js' {
  declare module.exports: $Exports<'rollup-plugin-copy/dist/index.module'>;
}
