// flow-typed signature: 548099e129d6f57ead44f4d1cffb2374
// flow-typed version: <<STUB>>/rollup-plugin-generate-package-json_v^3.2.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-generate-package-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-generate-package-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-generate-package-json/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-generate-package-json/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-generate-package-json/dist/index.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-generate-package-json/dist/index.cjs'>;
}
declare module 'rollup-plugin-generate-package-json/dist/index.esm.js' {
  declare module.exports: $Exports<'rollup-plugin-generate-package-json/dist/index.esm'>;
}
