// flow-typed signature: 4fee9d96781c0fd4f4670f843a692874
// flow-typed version: <<STUB>>/source-map-explorer_v^2.4.2/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-map-explorer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-map-explorer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'source-map-explorer/dist/api' {
  declare module.exports: any;
}

declare module 'source-map-explorer/dist/app-error' {
  declare module.exports: any;
}

declare module 'source-map-explorer/dist/cli' {
  declare module.exports: any;
}

declare module 'source-map-explorer/dist/coverage' {
  declare module.exports: any;
}

declare module 'source-map-explorer/dist/explore' {
  declare module.exports: any;
}

declare module 'source-map-explorer/dist/helpers' {
  declare module.exports: any;
}

declare module 'source-map-explorer/dist/html' {
  declare module.exports: any;
}

declare module 'source-map-explorer/dist' {
  declare module.exports: any;
}

declare module 'source-map-explorer/dist/output' {
  declare module.exports: any;
}

declare module 'source-map-explorer/dist/vendor/webtreemap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'source-map-explorer/dist/api.js' {
  declare module.exports: $Exports<'source-map-explorer/dist/api'>;
}
declare module 'source-map-explorer/dist/app-error.js' {
  declare module.exports: $Exports<'source-map-explorer/dist/app-error'>;
}
declare module 'source-map-explorer/dist/cli.js' {
  declare module.exports: $Exports<'source-map-explorer/dist/cli'>;
}
declare module 'source-map-explorer/dist/coverage.js' {
  declare module.exports: $Exports<'source-map-explorer/dist/coverage'>;
}
declare module 'source-map-explorer/dist/explore.js' {
  declare module.exports: $Exports<'source-map-explorer/dist/explore'>;
}
declare module 'source-map-explorer/dist/helpers.js' {
  declare module.exports: $Exports<'source-map-explorer/dist/helpers'>;
}
declare module 'source-map-explorer/dist/html.js' {
  declare module.exports: $Exports<'source-map-explorer/dist/html'>;
}
declare module 'source-map-explorer/dist/index' {
  declare module.exports: $Exports<'source-map-explorer/dist'>;
}
declare module 'source-map-explorer/dist/index.js' {
  declare module.exports: $Exports<'source-map-explorer/dist'>;
}
declare module 'source-map-explorer/dist/output.js' {
  declare module.exports: $Exports<'source-map-explorer/dist/output'>;
}
declare module 'source-map-explorer/dist/vendor/webtreemap.js' {
  declare module.exports: $Exports<'source-map-explorer/dist/vendor/webtreemap'>;
}
