// flow-typed signature: 3193dd26fee6216926ef47097ebc20bf
// flow-typed version: <<STUB>>/@reach/rect_v*/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/rect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/rect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/rect/dist' {
  declare module.exports: any;
}

declare module '@reach/rect/dist/rect.cjs.development' {
  declare module.exports: any;
}

declare module '@reach/rect/dist/rect.cjs.production.min' {
  declare module.exports: any;
}

declare module '@reach/rect/dist/rect.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/rect/dist/index' {
  declare module.exports: $Exports<'@reach/rect/dist'>;
}
declare module '@reach/rect/dist/index.js' {
  declare module.exports: $Exports<'@reach/rect/dist'>;
}
declare module '@reach/rect/dist/rect.cjs.development.js' {
  declare module.exports: $Exports<'@reach/rect/dist/rect.cjs.development'>;
}
declare module '@reach/rect/dist/rect.cjs.production.min.js' {
  declare module.exports: $Exports<'@reach/rect/dist/rect.cjs.production.min'>;
}
declare module '@reach/rect/dist/rect.esm.js' {
  declare module.exports: $Exports<'@reach/rect/dist/rect.esm'>;
}
