// flow-typed signature: e88c4053e997181fc9fc5dc5d63b3caa
// flow-typed version: <<STUB>>/@reach/visually-hidden_v^0.11.1/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/visually-hidden'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/visually-hidden' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/visually-hidden/dist' {
  declare module.exports: any;
}

declare module '@reach/visually-hidden/dist/visually-hidden.cjs.development' {
  declare module.exports: any;
}

declare module '@reach/visually-hidden/dist/visually-hidden.cjs.production.min' {
  declare module.exports: any;
}

declare module '@reach/visually-hidden/dist/visually-hidden.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/visually-hidden/dist/index' {
  declare module.exports: $Exports<'@reach/visually-hidden/dist'>;
}
declare module '@reach/visually-hidden/dist/index.js' {
  declare module.exports: $Exports<'@reach/visually-hidden/dist'>;
}
declare module '@reach/visually-hidden/dist/visually-hidden.cjs.development.js' {
  declare module.exports: $Exports<'@reach/visually-hidden/dist/visually-hidden.cjs.development'>;
}
declare module '@reach/visually-hidden/dist/visually-hidden.cjs.production.min.js' {
  declare module.exports: $Exports<'@reach/visually-hidden/dist/visually-hidden.cjs.production.min'>;
}
declare module '@reach/visually-hidden/dist/visually-hidden.esm.js' {
  declare module.exports: $Exports<'@reach/visually-hidden/dist/visually-hidden.esm'>;
}
