// flow-typed signature: 7a373a007bf77dfb392b7c8177ca32aa
// flow-typed version: <<STUB>>/@jsdevtools/npm-publish_v^1.1.0/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jsdevtools/npm-publish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jsdevtools/npm-publish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jsdevtools/npm-publish/bin/npm-publish' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/action' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/cli/exit-code' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/cli/help' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/cli' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/cli/parse-args' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/normalize-options' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/npm-config' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/npm-publish' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/npm' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/options' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/read-manifest' {
  declare module.exports: any;
}

declare module '@jsdevtools/npm-publish/lib/results' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jsdevtools/npm-publish/bin/npm-publish.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/bin/npm-publish'>;
}
declare module '@jsdevtools/npm-publish/lib/action/index' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/action'>;
}
declare module '@jsdevtools/npm-publish/lib/action/index.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/action'>;
}
declare module '@jsdevtools/npm-publish/lib/cli/exit-code.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/cli/exit-code'>;
}
declare module '@jsdevtools/npm-publish/lib/cli/help.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/cli/help'>;
}
declare module '@jsdevtools/npm-publish/lib/cli/index' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/cli'>;
}
declare module '@jsdevtools/npm-publish/lib/cli/index.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/cli'>;
}
declare module '@jsdevtools/npm-publish/lib/cli/parse-args.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/cli/parse-args'>;
}
declare module '@jsdevtools/npm-publish/lib/index' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib'>;
}
declare module '@jsdevtools/npm-publish/lib/index.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib'>;
}
declare module '@jsdevtools/npm-publish/lib/normalize-options.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/normalize-options'>;
}
declare module '@jsdevtools/npm-publish/lib/npm-config.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/npm-config'>;
}
declare module '@jsdevtools/npm-publish/lib/npm-publish.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/npm-publish'>;
}
declare module '@jsdevtools/npm-publish/lib/npm.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/npm'>;
}
declare module '@jsdevtools/npm-publish/lib/options.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/options'>;
}
declare module '@jsdevtools/npm-publish/lib/read-manifest.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/read-manifest'>;
}
declare module '@jsdevtools/npm-publish/lib/results.js' {
  declare module.exports: $Exports<'@jsdevtools/npm-publish/lib/results'>;
}
